Update command for version 0.0.3

diff --git a/chronom-cli b/chronom-cli
--- a/chronom-cli
+++ b/chronom-cli
@@ -950,7 +950,8 @@ chronom_cli_upgrade_usage() {
   echo
 
   printf "%s\n" "$(bold "Commands:")"
-  printf "  %s   Upgrade Chronom Version\n" "$(green "chronom")"
+  printf "  %s   Upgrade Chronom Version\n" "$(green "chronom")     "
+  printf "  %s   Upgrade Chronom Version\n" "$(green "chronom-temp")"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -985,6 +986,45 @@ chronom_cli_upgrade_chronom_usage() {
     printf "  %s\n" "$(yellow "--version, -v VERSION (required)")"
     printf "    The Chronom A.I. Version to upgrade to\n"
     echo
+
+    printf "  %s\n" "$(yellow "--cluster-name, -n CLUSTER-NAME (required)")"
+    printf "    The name of the EKS Cluster where chronom is installed - usually\n    chronom-cluster\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--region, -r REGION (required)")"
+    printf "    The AWS region where the EKS Cluster is located\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--namespace NAMESPACE")"
+    printf "    Namespace where chronom is installed - usually chronom\n"
+    printf "    Default: chronom\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+chronom_cli_upgrade_chronom_temp_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "chronom-cli upgrade chronom-temp - Upgrade Chronom Version\n"
+    echo
+
+  else
+    printf "chronom-cli upgrade chronom-temp - Upgrade Chronom Version\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  chronom-cli upgrade chronom-temp [OPTIONS]\n"
+  printf "  chronom-cli upgrade chronom-temp --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
 
     printf "  %s\n" "$(yellow "--cluster-name, -n CLUSTER-NAME (required)")"
     printf "    The name of the EKS Cluster where chronom is installed - usually\n    chronom-cluster\n"
@@ -1779,6 +1819,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'upgrade chronom-temp\'*\'--cluster-name\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'c chronom complete-deployment-eks\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--auto-validate --chronom-auth-id --chronom-namespace --chronom-readonly-username --chronom-registry-name --chronom-registry-username --chronom-version --create-rsa-key --dns-record --help --key-pair-name --max-nodes --min-nodes --name --node-type --region --skip-calico-setup --skip-certificate-setup --skip-gp3-setup --skip-ingress-setup --version -d -h -n -r -v")" -- "$cur" )'
   echo $'      ;;'
@@ -1797,6 +1841,10 @@ send_completions() {
   echo $''
   echo $'    \'configure kube-context\'*\'--name\')'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'upgrade chronom-temp\'*\'--region\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'create cluster-eks\'*\'--region\')'
@@ -1837,6 +1885,14 @@ send_completions() {
   echo $''
   echo $'    \'delete chronom user-iam\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --name -h -n")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'upgrade chronom-temp\'*\'-n\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'upgrade chronom-temp\'*\'-r\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'c cluster-eks\'*\'--region\')'
@@ -1885,6 +1941,10 @@ send_completions() {
   echo $''
   echo $'    \'configure k\'*\'--region\')'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'upgrade chronom-temp\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--cluster-name --help --namespace --region -h -n -r")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'setup auto-complete\'*)'
@@ -2020,7 +2080,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'upgrade\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h chronom")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h chronom chronom-temp")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'create\'*)'
@@ -2478,6 +2538,70 @@ chronom_cli_upgrade_chronom_command() {
 
   green "# Done! Chronom has been upgraded to version ${args[--version]} in cluster ${args[--cluster-name]}"
   green "# Note that it might take a moment for the new version to completly replace the old one"
+}
+
+chronom_cli_upgrade_chronom_temp_command() {
+  yellow "# Upgrading Chronom to version 0.0.3 in cluster ${args[--cluster-name]}"
+  yellow "# Updating kubeconfig to use the cluster ${args[--cluster-name]} in the region ${args[--region]}"
+
+  clusterName=${args[--cluster-name]}
+  region=${args[--region]}
+  version="0.0.3"
+  namespace=${args[--namespace]}
+
+  tags='[{"Key":"Application","Value":"Chronom A.I."},{"Key":"DeployedAt","Value":"UTC-'$(date --utc +%Y-%m-%d:%H:%M:%S)'"}]'
+
+  adminRoleArn=$(aws iam get-role --role-name $clusterName-AdminRole --query 'Role.Arn' --output text)
+  eksctl utils write-kubeconfig --cluster $clusterName --region $region --set-kubeconfig-context --authenticator-role-arn $adminRoleArn
+
+  kubectl config set-context --current --namespace $namespace
+
+  green "# Done! Proceeding to upgrade Chronom to version ${args[--version]} in cluster ${args[--cluster-name]}"
+
+  yellow "# Extracting relevant parameters from existing version"
+  chronomAuthId=$(kubectl get secrets auth-chronom-chronom-secret -o jsonpath='{.data.AUTH_CLIENT_ID}' | base64 -d)
+  green "# Organization ID: $chronomAuthId"
+
+  accountId=$(aws sts get-caller-identity --query 'Account' --output text)
+
+  secretContent=$(kubectl get secrets awsscanner-chronom-chronom-secret -o jsonpath='{.data}' | jq --arg organizationId "$chronomAuthId" --arg accountId "$accountId" -c '[{accessKeyId: (.AWS_ACCESS_KEY_ID | @base64d),  secretAccessKey: (.AWS_SECRET_ACCESS_KEY | @base64d),  roleArn: (.ROLE_ARN | @base64d),organizationId: $organizationId,accountId: $accountId}]')
+
+  green "# Successfuly constructed secret content"
+  yellow "# Creating Secret"
+  secretManagerArn=$(aws secretsmanager create-secret --name "aws-credentials-$chronomAuthId" --secret-string "$secretContent" --region "$region" --tags "$tags" --query 'ARN' --output text)
+  aws iam create-user --user-name "$clusterName-asm-ro-user" --tags "$tags"
+  roAccessKey=$(aws iam create-access-key --user-name "aws-credentials-$chronomAuthId-ro-user" --query '{accessKeyId:AccessKey.AccessKeyId, secretAccessKey:AccessKey.SecretAccessKey}' --output json)
+  roPolicyArn=$(aws iam create-policy --tags "$tags" --policy-name "aws-credentials-$chronomAuthId-ro-user-policy" --policy-document "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"readonly\",\"Effect\":\"Allow\",\"Action\":[\"secretsmanager:GetSecretValue\"],\"Resource\":\"$secretManagerArn\"}]}" --query 'Policy.Arn' --output text)
+  aws iam attach-user-policy --user-name "aws-credentials-$chronomAuthId-ro-user" --policy-arn "$roPolicyArn"
+  aws iam create-user --user-name "aws-credentials-$chronomAuthId-rw-user" --tags "$tags"
+  rwAccessKey=$(aws iam create-access-key --user-name "aws-credentials-$chronomAuthId-rw-user" --query '{accessKeyId:AccessKey.AccessKeyId, secretAccessKey:AccessKey.SecretAccessKey}' --output json)
+  rwPolicyArn=$(aws iam create-policy --policy-name "aws-credentials-$chronomAuthId-rw-user-policy" --tags "$tags" --policy-document "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"readonly\",\"Effect\":\"Allow\",\"Action\":[\"secretsmanager:GetSecretValue\",\"secretsmanager:UpdateSecret\",\"secretsmanager:PutSecretValue\"],\"Resource\":\"$secretManagerArn\"}]}" --query 'Policy.Arn' --output text)
+  aws iam attach-user-policy --user-name "aws-credentials-$chronomAuthId-rw-user" --policy-arn "$rwPolicyArn"
+  green "# Successfully created Secret Manager"
+
+  yellow "# Updating role IAM Policy"
+  curl -Os https://raw.githubusercontent.com/chronom-ai/chronom-cli/main/public_resources/readonly-policy.json
+
+  aws iam create-policy-version --policy-arn "arn:aws:iam::${accountId}:policy/${clusterName}-role-permissions-policy" --policy-document file://readonly-policy.json --set-as-default
+
+  rm readonly-policy.json
+
+  green "# Successfully updated role IAM Policy"
+
+  yellow "# Updating role permission over the cluster"
+  eksctl create iamidentitymapping --cluster "$clusterName" --arn "arn:aws:iam::${accountId}:role/${clusterName}-role" --group chronomReadOnlyGroup --username "${clusterName}-role"
+
+  yellow "# Extracting Chronom Helm registry credentials"
+  registryCredentials=$(kubectl get secret chronom-registry-key -n chronom -o jsonpath='{.data.\.dockerconfigjson}' | base64 --decode)
+
+  registryAddress=$(echo $registryCredentials | jq -r '.auths' | jq -r 'keys[0]')
+  registryUsername=$(echo $registryCredentials | jq -r '.auths' | jq -r '.[] | .username')
+  registryPassword=$(echo $registryCredentials | jq -r '.auths' | jq -r '.[] | .password')
+
+  helm registry login "$registryAddress" --username "$registryUsername" --password "$registryPassword"
+
+  helm upgrade -n "$namespace" chronom "oci://${registryAddress}/helm/chronom" --version "$version"  --set secretRegion=$region --set-json="backend=$rwAccessKey" --set-json "awsscanner=$roAccessKey"
+
 }
 
 chronom_cli_completions_command() {
@@ -4697,6 +4821,13 @@ chronom_cli_upgrade_parse_requirements() {
       shift $#
       ;;
 
+    chronom-temp)
+      action="chronom-temp"
+      shift
+      chronom_cli_upgrade_chronom_temp_parse_requirements "$@"
+      shift $#
+      ;;
+
     "")
       chronom_cli_upgrade_usage >&2
       exit 1
@@ -4886,6 +5017,145 @@ chronom_cli_upgrade_chronom_parse_requirements() {
 
 }
 
+chronom_cli_upgrade_chronom_temp_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        chronom_cli_upgrade_chronom_temp_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  if command -v aws >/dev/null 2>&1; then
+    deps['aws']="$(command -v aws | head -n1)"
+  else
+    printf "missing dependency: aws\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install awscli' to install aws cli and configure aws credentials - https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html#:~:text=an%20external%20process-,Setting%20up%20new%20configuration%20and%20credentials,-The%20AWS%20CLI
+  Alternatively you can install aws cli and configure aws credentials by following the official guide - https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html" >&2
+    exit 1
+  fi
+
+  if command -v kubectl >/dev/null 2>&1; then
+    deps['kubectl']="$(command -v kubectl | head -n1)"
+  else
+    printf "missing dependency: kubectl\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install kubectl' to install kubectl - https://kubernetes.io/docs/tasks/tools/install-kubectl/
+  Alternatively you can install kubectl by following the official guide - https://kubernetes.io/docs/tasks/tools/install-kubectl/" >&2
+    exit 1
+  fi
+
+  if command -v eksctl >/dev/null 2>&1; then
+    deps['eksctl']="$(command -v eksctl | head -n1)"
+  else
+    printf "missing dependency: eksctl\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install eksctl' to install eksctl - https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html
+  Alternatively you can install eksctl by following the official guide - https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html" >&2
+    exit 1
+  fi
+
+  if command -v helm >/dev/null 2>&1; then
+    deps['helm']="$(command -v helm | head -n1)"
+  else
+    printf "missing dependency: helm\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install helm' to install helm - https://helm.sh/docs/intro/install/
+  Alternatively you can install helm by following the official guide - https://helm.sh/docs/intro/install/" >&2
+    exit 1
+  fi
+
+  if command -v jq >/dev/null 2>&1; then
+    deps['jq']="$(command -v jq | head -n1)"
+  else
+    printf "missing dependency: jq\n" >&2
+    printf "%s\n" "Please install jq - https://stedolan.github.io/jq/download/" >&2
+    exit 1
+  fi
+
+  action="upgrade chronom-temp"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      --cluster-name | -n)
+
+        if [[ -n ${2+x} ]]; then
+
+          args['--cluster-name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-name requires an argument: --cluster-name, -n CLUSTER-NAME" >&2
+          exit 1
+        fi
+        ;;
+
+      --region | -r)
+
+        if [[ -n ${2+x} ]]; then
+
+          if [[ -n $(validate_available_aws_region "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--region, -r REGION" "$(validate_available_aws_region "$2")" >&2
+            exit 1
+          fi
+
+          args['--region']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--region requires an argument: --region, -r REGION" >&2
+          exit 1
+        fi
+        ;;
+
+      --namespace)
+
+        if [[ -n ${2+x} ]]; then
+
+          args['--namespace']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--namespace requires an argument: --namespace NAMESPACE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  if [[ -z ${args['--cluster-name']+x} ]]; then
+    printf "missing required flag: --cluster-name, -n CLUSTER-NAME\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--region']+x} ]]; then
+    printf "missing required flag: --region, -r REGION\n" >&2
+    exit 1
+  fi
+
+  [[ -n ${args['--namespace']:-} ]] || args['--namespace']="chronom"
+
+}
+
 chronom_cli_completions_parse_requirements() {
 
   while [[ $# -gt 0 ]]; do
@@ -4968,6 +5238,7 @@ run() {
     "configure kube-context") chronom_cli_configure_kube_context_command ;;
     "upgrade") chronom_cli_upgrade_command ;;
     "upgrade chronom") chronom_cli_upgrade_chronom_command ;;
+    "upgrade chronom-temp") chronom_cli_upgrade_chronom_temp_command ;;
     "completions") chronom_cli_completions_command ;;
   esac
 }
