added cloudshell command

diff --git a/chronom-cli b/chronom-cli
--- a/chronom-cli
+++ b/chronom-cli
@@ -33,7 +33,6 @@ chronom_cli_usage() {
   printf "  %s   List Resources\n" "$(green "list")  "
   printf "  %s   Delete Resources\n" "$(green "delete")"
   printf "  %s   Setup shell environment\n" "$(green "setup") "
-  printf "  %s   \n" "$(green "test")  "
   echo
 
   if [[ -n $long_usage ]]; then
@@ -313,7 +312,7 @@ chronom_cli_create_chronom_complete_deployment_eks_usage() {
 
     printf "  %s\n" "$(yellow "--chronom-registry-name CHRONOM-REGISTRY-NAME")"
     printf "    This value should only be set if instructed by Chronom A.I. support.\n"
-    printf "    Default: chronomproddemoacr.azurecr.io\n"
+    printf "    Default: chronomprodacr.azurecr.io\n"
     echo
 
     printf "  %s\n" "$(yellow "--skip-ingress-setup")"
@@ -551,6 +550,7 @@ chronom_cli_setup_usage() {
   printf "%s\n" "$(bold "Commands:")"
   printf "  %s   Setup auto-complete for chronom-cli\n" "$(green "auto-complete")"
   printf "  %s   Install dependencies\n" "$(green "install")      "
+  printf "  %s   Setup cloudshell environment with all dependencies for chronom-cli\n" "$(green "cloudshell")   "
   echo
 
   if [[ -n $long_usage ]]; then
@@ -730,6 +730,32 @@ chronom_cli_setup_install_helm_usage() {
   fi
 }
 
+chronom_cli_setup_cloudshell_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "chronom-cli setup cloudshell - Setup cloudshell environment with all dependencies for chronom-cli\n"
+    echo
+
+  else
+    printf "chronom-cli setup cloudshell - Setup cloudshell environment with all dependencies for chronom-cli\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  chronom-cli setup cloudshell\n"
+  printf "  chronom-cli setup cloudshell --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    printf "  %s\n" "$(yellow "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
 chronom_cli_completions_usage() {
   if [[ -n $long_usage ]]; then
     printf "chronom-cli completions\n"
@@ -751,36 +777,6 @@ chronom_cli_completions_usage() {
 
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
-
-    printf "  %s\n" "$(yellow "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
-  fi
-}
-
-chronom_cli_test_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "chronom-cli test\n"
-    echo
-
-  else
-    printf "chronom-cli test\n"
-    echo
-
-  fi
-
-  printf "%s\n" "$(bold "Usage:")"
-  printf "  chronom-cli test [OPTIONS]\n"
-  printf "  chronom-cli test --help | -h\n"
-  echo
-
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "$(bold "Options:")"
-
-    printf "  %s\n" "$(yellow "--region REGION")"
-    printf "\n"
-    echo
 
     printf "  %s\n" "$(yellow "--help, -h")"
     printf "    Show this help\n"
@@ -884,6 +880,7 @@ create_rsa_key_pair() {
     region="$2"
 
     check_available_key_pair_name $clusterName-KeyPair $region
+    mkdir -p ~/.ssh
     aws ec2 create-key-pair --key-name $clusterName-KeyPair --region $region --query "KeyMaterial" --output text > ~/.ssh/$clusterName-KeyPair.pem
     sshKeysFlags="--ssh-access --ssh-public-key $clusterName-KeyPair"
 }
@@ -1259,6 +1256,118 @@ find_create_compatible_dns_zone_cname() {
     fi
 }
 
+install_eksctl() {
+    yellow "# Checking eksctl version"
+    if command -v eksctl >/dev/null 2>&1; then
+        eksctl_version=$(eksctl version)
+        required_version="0.150.0"
+
+        if [[ "$(printf '%s\n' "$required_version" "$eksctl_version" | sort -V | tail -n 1)" == "$eksctl_version" ]]; then
+            green "# eksctl is installed and version is greater than or equal to $required_version"
+        else
+            blue "# eksctl version is less than $required_version, Installing newer version"
+            ARCH=amd64
+            PLATFORM=$(uname -s)_$ARCH
+
+            curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
+
+            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
+
+            sudo mv /tmp/eksctl /usr/local/bin
+
+            green "# Successfully installed eksctl locally"
+        fi
+    else
+        red "# eksctl is not installed, installing now"
+        # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
+        ARCH=amd64
+        PLATFORM=$(uname -s)_$ARCH
+
+        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
+
+        tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
+
+        sudo mv /tmp/eksctl /usr/local/bin
+
+        green "# Successfully installed eksctl locally"
+    fi
+
+}
+
+install_aws_cli() {
+    yellow "# Checking aws CLI version"
+    if command -v aws >/dev/null 2>&1; then
+        aws_cli_version=$(aws --version 2>&1 | cut -d/ -f2 | cut -d' ' -f1)
+        required_version="2.10.0"
+
+        if [[ "$(printf '%s\n' "$required_version" "$aws_cli_version" | sort -V | tail -n 1)" == "$aws_cli_version" ]]; then
+            green "# aws CLI is installed and version is greater than or equal to $required_version"
+        else
+            blue "# aws CLI version is less than $required_version, Installing newer version"
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+            green "# Successfully installed AWS CLI locally"
+        fi
+    else
+        red "# aws CLI is not installed, installing now"
+        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+        unzip awscliv2.zip
+        sudo ./aws/install
+        green "# Successfully installed AWS CLI locally"
+    fi
+}
+
+install_helm() {
+    yellow "# Checking helm version"
+    if command -v helm >/dev/null 2>&1; then
+        helm_version=$(helm version --template='{{.Version}}' | cut -c2-)
+        required_version="3.10.0"
+
+        if [[ "$(printf '%s\n' "$required_version" "$helm_version" | sort -V | tail -n 1)" == "$helm_version" ]]; then
+            green "# helm is installed and version is greater than or equal to $required_version"
+        else
+            blue "# helm version is less than $required_version, Installing newer version"
+            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+            chmod 700 get_helm.sh
+            ./get_helm.sh
+            green "# Successfully installed helm locally"
+        fi
+    else
+        red "# helm is not installed, installing now"
+        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+        chmod 700 get_helm.sh
+        ./get_helm.sh
+        green "# Successfully installed helm locally"
+    fi
+}
+
+install_kubectl() {
+    yellow "# Checking kubectl version"
+    if command -v kubectl >/dev/null 2>&1; then
+        kubectl_version=$(kubectl version --client=true --output yaml | grep -w "gitVersion" | awk '{print $2}' | cut -c2-)
+        required_version="1.25.0"
+
+        if [[ "$(printf '%s\n' "$required_version" "$kubectl_version" | sort -V | tail -n 1)" == "$kubectl_version" ]]; then
+            green "# kubectl is installed and version is greater than or equal to $required_version"
+        else
+            blue "# kubectl version is less than $required_version, Installing newer version"
+            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+
+            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+
+            green "# Successfully installed kubectl locally"
+        fi
+    else
+        red "# kubectl is not installed, installing now"
+        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+
+        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+
+        green "# Successfully installed kubectl locally"
+    fi
+}
+
 send_completions() {
   echo $'# chronom-cli completion                                   -*- shell-script -*-'
   echo $''
@@ -1442,6 +1551,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'setup cloudshell\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'s auto-complete\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --update-bashrc -h")" -- "$cur" )'
   echo $'      ;;'
@@ -1470,6 +1583,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h awscli eksctl helm kubectl")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'s cloudshell\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'c chronom\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h complete-deployment-eks user-iam")" -- "$cur" )'
   echo $'      ;;'
@@ -1491,15 +1608,11 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'setup\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete install")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete cloudshell install")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'list\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h cluster-eks")" -- "$cur" )'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'test\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --region -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'c\'*)'
@@ -1515,11 +1628,11 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'s\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete install")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete cloudshell install")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --version -h -v c create d delete l list s setup test")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --version -h -v c create d delete l list s setup")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -1838,44 +1951,33 @@ chronom_cli_setup_auto_complete_command() {
 }
 
 chronom_cli_setup_install_awscli_command() {
-  yellow "# Installing AWS CLI locally"
-  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-  unzip awscliv2.zip
-  sudo ./aws/install
-  green "# Successfully installed AWS CLI locally"
+  install_aws_cli
 }
 
 chronom_cli_setup_install_kubectl_command() {
-  yellow "# Installing kubectl locally"
-  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-
-  green install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+  install_kubectl
 }
 
 chronom_cli_setup_install_eksctl_command() {
-  yellow "# Installing eksctl locally"
-
-  # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
-  ARCH=amd64
-  PLATFORM=$(uname -s)_$ARCH
-
-  curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
-
-  tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
-
-  sudo mv /tmp/eksctl /usr/local/bin
-
-  green "# Successfully installed eksctl locally"
+  install_eksctl
 }
 
 chronom_cli_setup_install_helm_command() {
-  yellow "# Installing Helm locally"
+  install_helm
+}
 
-  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
-  chmod 700 get_helm.sh
-  ./get_helm.sh
+chronom_cli_setup_cloudshell_command() {
+  yellow "# Setting up AWS CloudShell with the required dependencies"
 
-  green "# Successfully installed Helm locally"
+  yellow "# Installing OpenSSL"
+
+  sudo yum install -y openssl
+
+  install_eksctl
+
+  install_helm
+
+  green "# Successfully configured AWS CloudShell with the required dependencies"
 }
 
 chronom_cli_completions_command() {
@@ -1888,11 +1990,6 @@ chronom_cli_completions_command() {
   #   $ eval "$(chronom-cli completions)"
   #
   send_completions
-}
-
-chronom_cli_test_command() {
-  echo " blue? $(blue_bold "#blue!")"
-  yellow "# Creating a new EKS Cluster in the $(red ${args[--region]}) region for Chronom"
 }
 
 parse_requirements() {
@@ -1954,13 +2051,6 @@ parse_requirements() {
       action="completions"
       shift
       chronom_cli_completions_parse_requirements "$@"
-      shift $#
-      ;;
-
-    test)
-      action="test"
-      shift
-      chronom_cli_test_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2743,7 +2833,7 @@ chronom_cli_create_chronom_complete_deployment_eks_parse_requirements() {
   [[ -n ${args['--max-nodes']:-} ]] || args['--max-nodes']="10"
   [[ -n ${args['--chronom-version']:-} ]] || args['--chronom-version']="0.0.1"
   [[ -n ${args['--chronom-namespace']:-} ]] || args['--chronom-namespace']="chronom"
-  [[ -n ${args['--chronom-registry-name']:-} ]] || args['--chronom-registry-name']="chronomproddemoacr.azurecr.io"
+  [[ -n ${args['--chronom-registry-name']:-} ]] || args['--chronom-registry-name']="chronomprodacr.azurecr.io"
 
 }
 
@@ -3188,6 +3278,13 @@ chronom_cli_setup_parse_requirements() {
       shift $#
       ;;
 
+    cloudshell)
+      action="cloudshell"
+      shift
+      chronom_cli_setup_cloudshell_parse_requirements "$@"
+      shift $#
+      ;;
+
     "")
       chronom_cli_setup_usage >&2
       exit 1
@@ -3566,13 +3663,13 @@ chronom_cli_setup_install_helm_parse_requirements() {
 
 }
 
-chronom_cli_completions_parse_requirements() {
+chronom_cli_setup_cloudshell_parse_requirements() {
 
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        chronom_cli_completions_usage
+        chronom_cli_setup_cloudshell_usage
         exit
         ;;
 
@@ -3583,7 +3680,39 @@ chronom_cli_completions_parse_requirements() {
     esac
   done
 
-  action="completions"
+  if command -v curl >/dev/null 2>&1; then
+    deps['curl']="$(command -v curl | head -n1)"
+  else
+    printf "missing dependency: curl\n" >&2
+    printf "%s\n" "install curl - https://curl.se/download.html" >&2
+    exit 1
+  fi
+
+  if command -v tar >/dev/null 2>&1; then
+    deps['tar']="$(command -v tar | head -n1)"
+  else
+    printf "missing dependency: tar\n" >&2
+    printf "%s\n" "install tar - https://linuxize.com/post/how-to-extract-unzip-tar-gz-file/" >&2
+    exit 1
+  fi
+
+  if command -v unzip >/dev/null 2>&1; then
+    deps['unzip']="$(command -v unzip | head -n1)"
+  else
+    printf "missing dependency: unzip\n" >&2
+    printf "%s\n" "install unzip - https://linuxize.com/post/how-to-install-and-use-unzip/" >&2
+    exit 1
+  fi
+
+  if command -v sudo >/dev/null 2>&1; then
+    deps['sudo']="$(command -v sudo | head -n1)"
+  else
+    printf "missing dependency: sudo\n" >&2
+    printf "%s\n" "if you are already root, you should be ashamed of yourself!" >&2
+    exit 1
+  fi
+
+  action="setup cloudshell"
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -3606,13 +3735,13 @@ chronom_cli_completions_parse_requirements() {
 
 }
 
-chronom_cli_test_parse_requirements() {
+chronom_cli_completions_parse_requirements() {
 
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        chronom_cli_test_usage
+        chronom_cli_completions_usage
         exit
         ;;
 
@@ -3623,24 +3752,11 @@ chronom_cli_test_parse_requirements() {
     esac
   done
 
-  action="test"
+  action="completions"
 
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-
-      --region)
-
-        if [[ -n ${2+x} ]]; then
-
-          args['--region']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--region requires an argument: --region REGION" >&2
-          exit 1
-        fi
-        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -3693,8 +3809,8 @@ run() {
     "setup install kubectl") chronom_cli_setup_install_kubectl_command ;;
     "setup install eksctl") chronom_cli_setup_install_eksctl_command ;;
     "setup install helm") chronom_cli_setup_install_helm_command ;;
+    "setup cloudshell") chronom_cli_setup_cloudshell_command ;;
     "completions") chronom_cli_completions_command ;;
-    "test") chronom_cli_test_command ;;
   esac
 }
 
