added dns validation

diff --git a/chronom-cli b/chronom-cli
--- a/chronom-cli
+++ b/chronom-cli
@@ -1642,6 +1642,10 @@ send_completions() {
   echo $'# ex: filetype=sh'
 }
 
+validate_available_dns_record() {
+    [[ $(echo "$1" | grep -o "\." | wc -l) -ge 2 ]] || echo "Please enter a valid DNS Record."
+}
+
 validate_available_aws_region() {
   [[ ! "$1" == "il-central-1" ]] || echo "At the time there is an unmitigated issue with the AWS API in this region. Please choose a different region."
 }
@@ -1759,18 +1763,18 @@ chronom_cli_create_chronom_complete_deployment_eks_command() {
       read -s chronomAuthSecret
   done
 
-  chronomAuthSecretLength=${#chronomAuthSecret}
-  chronomAuthMasked=$(printf '*%.0s' $(seq 1 $((chronomAuthSecretLength - 4))))
-  magenta_underlined "\n Chronom Auth Secret: ${chronomAuthSecret:0:2}${chronomAuthMasked}${chronomAuthSecret: -2}"
-  magenta_underlined "Chronom Auth Secret length: ${#chronomAuthSecret}"
-  magenta_underlined "Is this correct? (y/n)"
-  read authAnswer
-  if [ "$authAnswer" != "${authAnswer#[Yy]}" ] ;then
-      green "Continuing..."
-  else
-      red_bold "Exiting..."
-      exit 1
-  fi
+  # # chronomAuthSecretLength=${#chronomAuthSecret}
+  # # chronomAuthMasked=$(printf '*%.0s' $(seq 1 $((chronomAuthSecretLength - 4))))
+  # # cyan_underlined "\n Chronom Auth Secret: ${chronomAuthSecret:0:2}${chronomAuthMasked}${chronomAuthSecret: -2}"
+  # # cyan_underlined "Chronom Auth Secret length: ${#chronomAuthSecret}"
+  # # cyan_underlined "Is this correct? (y/n)"
+  # # read authAnswer
+  # # if [ "$authAnswer" != "${authAnswer#[Yy]}" ] ;then
+  # #     green "Continuing..."
+  # # else
+  # #     red_bold "Exiting..."
+  # #     exit 1
+  # # fi
 
   echo
 
@@ -1784,20 +1788,20 @@ chronom_cli_create_chronom_complete_deployment_eks_command() {
       read -s chronomRegistryPassword
   done
 
-  chronomRegistryPasswordLength=${#chronomRegistryPassword}
-  chronomRegistryMasked=$(printf '*%.0s' $(seq 1 $((chronomRegistryPasswordLength - 4))))
+  # # chronomRegistryPasswordLength=${#chronomRegistryPassword}
+  # # chronomRegistryMasked=$(printf '*%.0s' $(seq 1 $((chronomRegistryPasswordLength - 4))))
 
-  magenta_underlined "\n Chronom Registry Password: ${chronomRegistryPassword:0:2}${chronomRegistryMasked}${chronomRegistryPassword: -2}"
-  magenta_underlined "Chronom Registry Password length: ${#chronomRegistryPassword}"
-  magenta_underlined "Is this correct? (y/n)"
-  read registryAnswer
-  if [ "$registryAnswer" != "${registryAnswer#[Yy]}" ] ;then
-      green "Continuing..."
-  else
-      red_bold "Exiting..."
-      exit 1
-  fi
-  echo
+  # # cyan_underlined "\n Chronom Registry Password: ${chronomRegistryPassword:0:2}${chronomRegistryMasked}${chronomRegistryPassword: -2}"
+  # # cyan_underlined "Chronom Registry Password length: ${#chronomRegistryPassword}"
+  # # cyan_underlined "Is this correct? (y/n)"
+  # # read registryAnswer
+  # # if [ "$registryAnswer" != "${registryAnswer#[Yy]}" ] ;then
+  # #     green "Continuing..."
+  # # else
+  # #     red_bold "Exiting..."
+  # #     exit 1
+  # # fi
+  # # echo
 
   create_cluster_complete $clusterName $region $version $nodeType $minNodes $maxNodes $accountId
 
@@ -2693,6 +2697,11 @@ chronom_cli_create_chronom_complete_deployment_eks_parse_requirements() {
       --dns-record | -d)
 
         if [[ -n ${2+x} ]]; then
+
+          if [[ -n $(validate_available_dns_record "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--dns-record, -d DNS-RECORD" "$(validate_available_dns_record "$2")" >&2
+            exit 1
+          fi
 
           args['--dns-record']="$2"
           shift
