Add kubecontext

diff --git a/chronom-cli b/chronom-cli
--- a/chronom-cli
+++ b/chronom-cli
@@ -809,7 +809,8 @@ chronom_cli_configure_usage() {
   echo
 
   printf "%s\n" "$(bold "Commands:")"
-  printf "  %s   Configure an Object to use Chronom A.I.\n" "$(green "chronom")"
+  printf "  %s   Configure an Object to use Chronom A.I.\n" "$(green "chronom")     "
+  printf "  %s   Configure the current Kubernetes context to use Chronom A.I.\n" "$(green "kube-context")"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -881,6 +882,47 @@ chronom_cli_configure_chronom_additional_cluster_eks_usage() {
 
     printf "  %s\n" "$(yellow "--chronom-readonly-username CHRONOM-READONLY-USERNAME (required)")"
     printf "    The name of the Chronom Read Only User to configure.\n    Usually this is the name of the cluster with '-ro-user' appended.\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+chronom_cli_configure_kube_context_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "chronom-cli configure kube-context - Configure the current Kubernetes context to use Chronom A.I.\n"
+    echo
+
+  else
+    printf "chronom-cli configure kube-context - Configure the current Kubernetes context to use Chronom A.I.\n"
+    echo
+
+  fi
+
+  printf "Alias: k\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  chronom-cli configure kube-context [OPTIONS]\n"
+  printf "  chronom-cli configure kube-context --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    printf "  %s\n" "$(yellow "--name, -n NAME (required)")"
+    printf "    The name of the EKS Cluster to configure\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--region, -r REGION (required)")"
+    printf "    The AWS region where the EKS Cluster is located\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--use-admin-role")"
+    printf "    Only for Chronom Cluster - Use the Admin Role to configure the Kubernetes\n    context\n"
     echo
 
     printf "  %s\n" "$(yellow "--help, -h")"
@@ -1586,8 +1628,16 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--auto-validate --chronom-auth-id --chronom-namespace --chronom-readonly-username --chronom-registry-name --chronom-registry-username --chronom-version --create-rsa-key --dns-record --help --key-pair-name --max-nodes --min-nodes --name --node-type --region --skip-calico-setup --skip-certificate-setup --skip-gp3-setup --skip-ingress-setup --version -d -h -n -r -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'configure kube-context\'*\'--region\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'create chronom user-iam\'*\'--name\')'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-readonly-user")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'configure kube-context\'*\'--name\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'create cluster-eks\'*\'--region\')'
@@ -1610,6 +1660,14 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-readonly-user")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'configure kube-context\'*\'-n\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'configure kube-context\'*\'-r\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'create chronom user-iam\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --name -h -n")" -- "$cur" )'
   echo $'      ;;'
@@ -1624,6 +1682,10 @@ send_completions() {
   echo $''
   echo $'    \'create certificate-acm\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--auto-validate --dns-record --help --region -d -h -r")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'configure kube-context\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --name --region --use-admin-role -h -n -r")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'create cluster-eks\'*\'-n\')'
@@ -1658,6 +1720,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'configure k\'*\'--region\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'setup auto-complete\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --update-bashrc -h")" -- "$cur" )'
   echo $'      ;;'
@@ -1676,6 +1742,10 @@ send_completions() {
   echo $''
   echo $'    \'setup install helm\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'configure k\'*\'--name\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'c certificate-acm\'*)'
@@ -1730,6 +1800,14 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'configure k\'*\'-n\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "chronom-cluster")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'configure k\'*\'-r\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "eu-north-1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'c cluster-eks\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--create-rsa-key --help --key-pair-name --max-nodes --min-nodes --name --node-type --region --skip-calico-setup --skip-gp3-setup --version -h -n -r -v")" -- "$cur" )'
   echo $'      ;;'
@@ -1746,6 +1824,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'configure k\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help --name --region --use-admin-role -h -n -r")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'c chronom\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h complete-deployment-eks user-iam")" -- "$cur" )'
   echo $'      ;;'
@@ -1759,7 +1841,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'configure\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h chronom")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h chronom k kube-context")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'create\'*)'
@@ -2186,6 +2268,25 @@ chronom_cli_configure_chronom_additional_cluster_eks_command() {
   chronomReadonlyClusterRole $clusterName $region $chronomReadonlyUsername
 
   green "# Done, You can now Scan the cluster with Chronom"
+}
+
+chronom_cli_configure_kube_context_command() {
+  yellow "# Configuring Local Kubectl Context to use the Cluster ${args[--name]} in the region ${args[--region]}"
+
+  clusterName=${args[--name]}
+  region=${args[--region]}
+
+  if [ -z "${args[--use-admin-role]}" ]; then
+      yellow "# Using the Admin role $clusterName-AdminRole"
+      adminRoleArn=$(aws iam get-role --role-name $clusterName-AdminRole --query 'Role.Arn' --output text)
+      adminRoleArnFlag="--authenticator-role-arn $adminRoleArn"
+  fi
+
+  yellow "# Updating kubeconfig"
+
+  eksctl utils write-kubeconfig --cluster $clusterName --region $region --set-kubeconfig-context $adminRoleArnFlag
+
+  green "# Done! You can now use kubectl / Helm to manage $clusterName"
 }
 
 chronom_cli_completions_command() {
@@ -4062,6 +4163,13 @@ chronom_cli_configure_parse_requirements() {
       shift $#
       ;;
 
+    kube-context | k)
+      action="kube-context"
+      shift
+      chronom_cli_configure_kube_context_parse_requirements "$@"
+      shift $#
+      ;;
+
     "")
       chronom_cli_configure_usage >&2
       exit 1
@@ -4249,6 +4357,119 @@ chronom_cli_configure_chronom_additional_cluster_eks_parse_requirements() {
 
 }
 
+chronom_cli_configure_kube_context_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        chronom_cli_configure_kube_context_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  if command -v kubectl >/dev/null 2>&1; then
+    deps['kubectl']="$(command -v kubectl | head -n1)"
+  else
+    printf "missing dependency: kubectl\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install kubectl' to install kubectl - https://kubernetes.io/docs/tasks/tools/install-kubectl/
+  Alternatively you can install kubectl by following the official guide - https://kubernetes.io/docs/tasks/tools/install-kubectl/" >&2
+    exit 1
+  fi
+
+  if command -v aws >/dev/null 2>&1; then
+    deps['aws']="$(command -v aws | head -n1)"
+  else
+    printf "missing dependency: aws\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install awscli' to install aws cli and configure aws credentials - https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html#:~:text=an%20external%20process-,Setting%20up%20new%20configuration%20and%20credentials,-The%20AWS%20CLI
+  Alternatively you can install aws cli and configure aws credentials by following the official guide - https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html" >&2
+    exit 1
+  fi
+
+  if command -v eksctl >/dev/null 2>&1; then
+    deps['eksctl']="$(command -v eksctl | head -n1)"
+  else
+    printf "missing dependency: eksctl\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install eksctl' to install eksctl - https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html
+  Alternatively you can install eksctl by following the official guide - https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html" >&2
+    exit 1
+  fi
+
+  action="configure kube-context"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      --name | -n)
+
+        if [[ -n ${2+x} ]]; then
+
+          args['--name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
+          exit 1
+        fi
+        ;;
+
+      --region | -r)
+
+        if [[ -n ${2+x} ]]; then
+
+          if [[ -n $(validate_available_aws_region "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--region, -r REGION" "$(validate_available_aws_region "$2")" >&2
+            exit 1
+          fi
+
+          args['--region']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--region requires an argument: --region, -r REGION" >&2
+          exit 1
+        fi
+        ;;
+
+      --use-admin-role)
+
+        args['--use-admin-role']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  if [[ -z ${args['--name']+x} ]]; then
+    printf "missing required flag: --name, -n NAME\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--region']+x} ]]; then
+    printf "missing required flag: --region, -r REGION\n" >&2
+    exit 1
+  fi
+
+}
+
 chronom_cli_completions_parse_requirements() {
 
   while [[ $# -gt 0 ]]; do
@@ -4328,6 +4549,7 @@ run() {
     "configure") chronom_cli_configure_command ;;
     "configure chronom") chronom_cli_configure_chronom_command ;;
     "configure chronom additional-cluster-eks") chronom_cli_configure_chronom_additional_cluster_eks_command ;;
+    "configure kube-context") chronom_cli_configure_kube_context_command ;;
     "completions") chronom_cli_completions_command ;;
   esac
 }
