Fix configure additional clusters command

diff --git a/chronom-cli b/chronom-cli
--- a/chronom-cli
+++ b/chronom-cli
@@ -588,6 +588,7 @@ chronom_cli_setup_usage() {
   printf "  %s   Setup auto-complete for chronom-cli\n" "$(green "auto-complete")"
   printf "  %s   Install dependencies\n" "$(green "install")      "
   printf "  %s   Setup cloudshell environment with all dependencies for chronom-cli\n" "$(green "cloudshell")   "
+  printf "  %s   Installs dig\n" "$(green "dig")          "
   echo
 
   if [[ -n $long_usage ]]; then
@@ -793,6 +794,32 @@ chronom_cli_setup_cloudshell_usage() {
   fi
 }
 
+chronom_cli_setup_dig_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "chronom-cli setup dig - Installs dig\n"
+    echo
+
+  else
+    printf "chronom-cli setup dig - Installs dig\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  chronom-cli setup dig\n"
+  printf "  chronom-cli setup dig --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    printf "  %s\n" "$(yellow "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
 chronom_cli_configure_usage() {
   if [[ -n $long_usage ]]; then
     printf "chronom-cli configure - Configure resources using chronom-cli\n"
@@ -883,6 +910,10 @@ chronom_cli_configure_chronom_additional_cluster_eks_usage() {
 
     printf "  %s\n" "$(yellow "--chronom-readonly-roleArn CHRONOM-READONLY-ROLEARN (required)")"
     printf "    The ARN of the Chronom Read Only Role.\n    This value is shown in the property \"clusterCommand\" in the EKS object in\n    chronom.\n"
+    echo
+
+    printf "  %s\n" "$(yellow "--chronom-public-ip CHRONOM-PUBLIC-IP")"
+    printf "    The Public Ip address of chronom.\n    If not provided in the EKS Cluster clusterCommand object, please find it by\n    going to the EKS Cluster in your AWS Console.\n"
     echo
 
     printf "  %s\n" "$(yellow "--help, -h")"
@@ -1213,6 +1244,7 @@ configure_additional_cluster_eks() {
     clusterName="$1"
     region="$2"
     chronomReadonlyRoleArn="$3"
+    chronomPublicIp="$4"
 
     chronomReadOnlyRoleName=$(echo "$chronomReadonlyRoleArn" | cut -d'/' -f2)
 
@@ -1224,6 +1256,48 @@ configure_additional_cluster_eks() {
     pemFile=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).pem
     echo $certificate | base64 -d > $pemFile
     green "# Temporary Credentials generated successfully"
+
+    if [[ -z $chronomPublicIp ]]; then
+
+        yellow "# Checking wether the cluster is private or public"
+        endpointIp=$(dig +short "$(echo $endpoint | sed 's/https:\/\///g')" | head -n1)
+        if [[ $endpointIp =~ ^10\. || $endpointIp =~ ^172\.1[6-9]\. || $endpointIp =~ ^172\.2[0-9]\. || $endpointIp =~ ^172\.3[0-1]\. || $endpointIp =~ ^192\.168\. ]]; then
+            red "# Cluster is private"
+            red "# Unfortunately, we do not support private clusters at the moment"
+            red "# Please add --chronom-public-ip and the public IP of Chronom to the command and try again"
+            exit 1
+        else
+            green "# Cluster is reachable from the internet"
+            green "# Proceeding with the configuration"
+        fi
+    fi
+
+    if [[ -n $chronomPublicIp ]]; then
+        yellow "# Configuring the cluster to be accessible only from Chronom's IP"
+        yellow "# This will take a few minutes, please stand by"
+        eksctl utils set-public-access-cidrs --cluster "$clusterName" --region "$region" "$chronomPublicIp" --aprove
+        eksctl utils update-cluster-endpoints --cluster "$clusterName" --region "$region" --public-access=true --private-access=true --approve
+        green "# Cluster configured to be accessible only from Chronom's IP"
+        yellow "# Checking wether user has access to the cluster"
+        canI=$(kubectl --server $endpoint --token $token --certificate-authority $pemFile auth can-i '*' '*' --all-namespaces || echo "no")
+        if [ "$canI" == "no" ]; then
+            red "# User does not have access to the cluster"
+            red "# Please execute the command with a user that has access to the cluster"
+            red "# You may locate that information by going trough your Account's CloudTrail Event History - CreateCluster API calls"
+            red "# For more information please go to - https://www.doit.com/resolving-the-your-current-user-or-role-does-not-have-access-to-kubernetes-objects-problem-on-aws-eks/"
+            exit 1
+        fi
+        green "# User has access to the cluster, proceeding with the configuration"
+    else
+        yellow "# Checking wether user has access to the cluster"
+        canI=$(kubectl --server $endpoint --token $token --certificate-authority $pemFile auth can-i '*' '*' --all-namespaces || echo "no")
+        if [ "$canI" == "no" ]; then
+            red "# User does not have access to the cluster"
+            red "# Please execute the command with a user that has access to the cluster"
+            exit 1
+        fi
+        green "# User has access to the cluster, proceeding with the configuration"
+    fi
 
   kubectl --server $endpoint --token $token --certificate-authority $pemFile apply -f - <<EOF
 apiVersion: rbac.authorization.k8s.io/v1
@@ -1738,6 +1812,27 @@ install_kubectl() {
     fi
 }
 
+install_dig() {
+    yellow "# Checking OS package manager"
+    if command -v apt >/dev/null 2>&1; then
+        yellow "# Detected apt package manager"
+        yellow "# Installing dig"
+        sudo apt update
+        sudo apt install -y dnsutils
+        green "# Successfully installed dig"
+    elif command -v yum >/dev/null 2>&1; then
+        yellow "# Detected yum package manager"
+        yellow "# Installing dig"
+        sudo yum update
+        sudo yum install -y bind-utils
+        green "# Successfully installed dig"
+    else
+        red "# OS package manager not found"
+        red "# Please install bind-utils manually"
+        exit 1
+    fi
+}
+
 check_available_cluster_name() {
     clusterName="$1"
     region="$2"
@@ -1820,7 +1915,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'configure chronom additional-cluster-eks\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--chronom-readonly-roleArn --cluster-name --help --region -h")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--chronom-public-ip --chronom-readonly-roleArn --cluster-name --help --region -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'create chronom complete-deployment-eks\'*)'
@@ -2091,6 +2186,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h awscli eksctl helm kubectl")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'setup dig\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'configure\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h chronom k kube-context")" -- "$cur" )'
   echo $'      ;;'
@@ -2108,7 +2207,11 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'setup\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete cloudshell install")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete cloudshell dig install")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s dig\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'list\'*)'
@@ -2128,7 +2231,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'s\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete cloudshell install")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_chronom-cli_completions_filter "--help -h auto-complete cloudshell dig install")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    *)'
@@ -2228,15 +2331,15 @@ chronom_cli_create_chronom_user_iam_command() {
 }
 
 chronom_cli_create_chronom_complete_deployment_eks_command() {
-  green_bold "# Thank you for choosing Chronom"
-  green_bold '# Please type "yes" to confirm your concent to Chronom`s Terms of Use and EULA'
-  read -r tmsEula
-  echo
-  if [ "${tmsEula,,}" != "yes" ]; then
-      red_bold 'You must agree to Chronom`s Terms of Use and EULA to proceed'
-      exit 1
-  fi
-  green '# Thank you for agreeing to Chronom`s Terms of Use and EULA'
+  # # green_bold "# Thank you for choosing Chronom"
+  # # green_bold '# Please type "yes" to confirm your concent to Chronom`s Terms of Use and EULA'
+  # # read -r tmsEula
+  # # echo
+  # # if [ "${tmsEula,,}" != "yes" ]; then
+  # #     red_bold 'You must agree to Chronom`s Terms of Use and EULA to proceed'
+  # #     exit 1
+  # # fi
+  # # green '# Thank you for agreeing to Chronom`s Terms of Use and EULA'
   yellow "# Creating a new EKS Cluster in the ${args[--region]} region for Chronom"
   yellow "# Cluster Name: ${args[--name]}"
   yellow "# Cluster Version: ${args[--version]}"
@@ -2509,11 +2612,17 @@ chronom_cli_setup_cloudshell_command() {
 
   sudo yum install -y openssl
 
+  install_dig
+
   install_eksctl
 
   install_helm
 
   green "# Successfully configured AWS CloudShell with the required dependencies"
+}
+
+chronom_cli_setup_dig_command() {
+  install_dig
 }
 
 chronom_cli_configure_chronom_additional_cluster_eks_command() {
@@ -2523,7 +2632,16 @@ chronom_cli_configure_chronom_additional_cluster_eks_command() {
   region=${args[--region]}
   chronomReadonlyRoleArn=${args[--chronom-readonly-roleArn]}
 
-  configure_additional_cluster_eks "$clusterName" "$region" "$chronomReadonlyRoleArn"
+  if [[ -n ${args[--chronom-public-ip]} ]]; then
+      chronomPublicIp=${args[--chronom-public-ip]}/32
+      yellow_bold "# You have provided a public IP for Chronom: $chronomPublicIp"
+      red_bold "# NOTE! This will convert your cluster to be Public, but only accessible from Chronom's IP"
+      red_bold "# If you have any other IP that should/already has access, please press CTRL+C and contact Chronom support for specific instructions"
+      yellow_bold "# Please press enter to continue, or CTRL+C to cancel"
+      read -r
+  fi
+
+  configure_additional_cluster_eks "$clusterName" "$region" "$chronomReadonlyRoleArn" "$chronomPublicIp"
 
   green "# Done, You can now Scan the cluster with Chronom"
 }
@@ -4040,6 +4158,13 @@ chronom_cli_setup_parse_requirements() {
       shift $#
       ;;
 
+    dig)
+      action="dig"
+      shift
+      chronom_cli_setup_dig_parse_requirements "$@"
+      shift $#
+      ;;
+
     "")
       chronom_cli_setup_usage >&2
       exit 1
@@ -4435,6 +4560,46 @@ chronom_cli_setup_cloudshell_parse_requirements() {
     esac
   done
 
+  action="setup cloudshell"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+chronom_cli_setup_dig_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        chronom_cli_setup_dig_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   if command -v curl >/dev/null 2>&1; then
     deps['curl']="$(command -v curl | head -n1)"
   else
@@ -4467,7 +4632,7 @@ chronom_cli_setup_cloudshell_parse_requirements() {
     exit 1
   fi
 
-  action="setup cloudshell"
+  action="setup dig"
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -4576,6 +4741,42 @@ chronom_cli_configure_chronom_parse_requirements() {
     esac
   done
 
+  if command -v aws >/dev/null 2>&1; then
+    deps['aws']="$(command -v aws | head -n1)"
+  else
+    printf "missing dependency: aws\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install awscli' to install aws cli and configure aws credentials - https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html#:~:text=an%20external%20process-,Setting%20up%20new%20configuration%20and%20credentials,-The%20AWS%20CLI
+  Alternatively you can install aws cli and configure aws credentials by following the official guide - https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html" >&2
+    exit 1
+  fi
+
+  if command -v kubectl >/dev/null 2>&1; then
+    deps['kubectl']="$(command -v kubectl | head -n1)"
+  else
+    printf "missing dependency: kubectl\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install kubectl' to install kubectl - https://kubernetes.io/docs/tasks/tools/install-kubectl/
+  Alternatively you can install kubectl by following the official guide - https://kubernetes.io/docs/tasks/tools/install-kubectl/" >&2
+    exit 1
+  fi
+
+  if command -v eksctl >/dev/null 2>&1; then
+    deps['eksctl']="$(command -v eksctl | head -n1)"
+  else
+    printf "missing dependency: eksctl\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install eksctl' to install eksctl - https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html
+  Alternatively you can install eksctl by following the official guide - https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html" >&2
+    exit 1
+  fi
+
+  if command -v dig >/dev/null 2>&1; then
+    deps['dig']="$(command -v dig | head -n1)"
+  else
+    printf "missing dependency: dig\n" >&2
+    printf "%s\n" "Please run './chronom-cli setup install dig' to install dig - https://linuxize.com/post/how-to-use-dig-command-to-query-dns-in-linux/
+  Alternatively you can install dig by following the official guide - https://linuxize.com/post/how-to-use-dig-command-to-query-dns-in-linux/" >&2
+    exit 1
+  fi
+
   action=${1:-}
 
   case $action in
@@ -4679,6 +4880,19 @@ chronom_cli_configure_chronom_additional_cluster_eks_parse_requirements() {
           shift
         else
           printf "%s\n" "--chronom-readonly-roleArn requires an argument: --chronom-readonly-roleArn CHRONOM-READONLY-ROLEARN" >&2
+          exit 1
+        fi
+        ;;
+
+      --chronom-public-ip)
+
+        if [[ -n ${2+x} ]]; then
+
+          args['--chronom-public-ip']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--chronom-public-ip requires an argument: --chronom-public-ip CHRONOM-PUBLIC-IP" >&2
           exit 1
         fi
         ;;
@@ -5283,6 +5497,7 @@ run() {
     "setup install eksctl") chronom_cli_setup_install_eksctl_command ;;
     "setup install helm") chronom_cli_setup_install_helm_command ;;
     "setup cloudshell") chronom_cli_setup_cloudshell_command ;;
+    "setup dig") chronom_cli_setup_dig_command ;;
     "configure") chronom_cli_configure_command ;;
     "configure chronom") chronom_cli_configure_chronom_command ;;
     "configure chronom additional-cluster-eks") chronom_cli_configure_chronom_additional_cluster_eks_command ;;
